INSERT INTO POKEMON(pokemonid,partyid,name,item,ability,move1,move2,move3,move4) VALUES('1','1','ランドロス霊','こだわりスカーフ','いかく','じしん','いわなだれ','ばかぢから','とんぼがえり');
INSERT INTO POKEMON(pokemonid,partyid,name,item,ability,move1,move2,move3,move4) VALUES('2','1','リザードン','メガストーンY','もうか','かえんほうしゃ','エアスラッシュ','おいかぜ','まもる');
INSERT INTO POKEMON(pokemonid,partyid,name,item,ability,move1,move2,move3,move4) VALUES('3','1','ニンフィア','こだわりメガネ','フェアリースキン','ハイパーボイス','ムーンフォース','シャドーボール','はかいこうせん');
INSERT INTO POKEMON(pokemonid,partyid,name,item,ability,move1,move2,move3,move4) VALUES('4','2','ブルンゲル','ナモのみ','ちょすい','シャドーボール','おにび','じこさいせい','トリックルーム');
INSERT INTO POKEMON(pokemonid,partyid,name,item,ability,move1,move2,move3,move4) VALUES('5','2','ハリテヤマ','とつげきチョッキ','あついしぼう','インファイト','はたきおとす','フェイント','ねこだまし');
INSERT INTO POKEMON(pokemonid,partyid,name,item,ability,move1,move2,move3,move4) VALUES('6','2','ヘラクロス','かえんだま','こんじょう','インファイト','はたきおとす','フェイント','メガホーン');
INSERT INTO POKEMON(pokemonid,partyid,name,item,ability,move1,move2,move3,move4) VALUES('7','3','ランドロス霊','とつげきチョッキ','いかく','じしん','いわなだれ','ばかぢから','はたきおとす');
INSERT INTO POKEMON(pokemonid,partyid,name,item,ability,move1,move2,move3,move4) VALUES('8','3','リザードン','メガストーンY','サンパワー','かえんほうしゃ','ソーラービーム','まもる','ねっぷう');
INSERT INTO POKEMON(pokemonid,partyid,name,item,ability,move1,move2,move3,move4) VALUES('9','3','ブルンゲル','オボンのみ','のろわれボディ','シャドーボール','しおふき','じこさいせい','トリックルーム');