INSERT INTO POKEMON(ID,NAME) VALUES('1','ランドロス霊');
INSERT INTO POKEMON(ID,NAME) VALUES('2','リザードン');
INSERT INTO POKEMON(ID,NAME) VALUES('3','ブルンゲル');
INSERT INTO POKEMON(ID,NAME) VALUES('4','ヒードラン');
INSERT INTO POKEMON(ID,NAME) VALUES('5','ハリテヤマ');
INSERT INTO POKEMON(ID,NAME) VALUES('6','ニンフィア');